/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tourism_app;

import javax.swing.JComboBox;

/**
 *
 * @author Shahriar
 */
public class bookinfoframe extends javax.swing.JFrame {

    String Combo1[];
    getConnection gc = new getConnection();
    /**
     * Creates new form bookinfoframe
     */
    public bookinfoframe() {
        gc.setstringData("SELECT location from accomodation group by location");
        Combo1 = Tourism_App.sqlstringData;
        
        initComponents();
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton4.setForeground(new java.awt.Color(15, 7, 239));
        jButton4.setText("All Bookings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 70, 150, 23);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(Combo1));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(420, 210, 200, 20);

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(36, 214, 60));
        jLabel14.setText("Location:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 210, 80, 30);

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(23, 229, 240));
        jLabel13.setText("Accomodation:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(690, 210, 110, 30);

        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(810, 210, 200, 20);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable8.setEnabled(false);
        jScrollPane1.setViewportView(jTable8);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 280, 590, 320);

        jButton3.setText("DONE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1163, 653, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/city.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        gc.set2DData("select booking_id, u_name, acco_name, booking_date from booking natural join accomodation "
            + "natural join project_users");
        Object []columnNames4 = { "ID", "Name", "Accomodation", "Date of Booking" };
        jTable8.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable8.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames4));
        jTable8.setEnabled(false);
        jScrollPane1.setViewportView(jTable8);

        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        //System.out.println(selected);
        gc.setstringData("select acco_name from accomodation where location = '"+selected+"'");
        jComboBox7.setVisible(true);
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(Tourism_App.sqlstringData));
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        String selected = (String)jComboBox7.getSelectedItem();
        gc.set2DData("select booking_id, u_name, acco_name, booking_date from booking natural join accomodation "
            + "natural join project_users where acco_name = '"+selected+"'");
        Object []columnNames4 = { "ID", "Name", "Accomodation", "Date of Booking" };
        jTable8.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable8.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames4));
        jTable8.setEnabled(false);
        jScrollPane1.setViewportView(jTable8);

        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookinfoframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookinfoframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookinfoframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookinfoframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookinfoframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable8;
    // End of variables declaration//GEN-END:variables
}
