package tourism_app;

import java.awt.Color;
import javax.swing.*;
import java.awt.Image;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author talha
 */
public class HomePage extends javax.swing.JFrame {

    getConnection gc;
    static String Combo1[];
    String Combo2[];
    String Combo3[];
    String Combo4[];
    String Combo5[];
    static String u_name;
    int piccount;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        //DataBase Connection
        gc = new getConnection();
        gc.setstringData("SELECT location from accomodation group by location");
        Combo1 = Tourism_App.sqlstringData;
        gc.setstringData("SELECT location from restaurant group by location");
        Combo2 = Tourism_App.sqlstringData;
        gc.setstringData("SELECT location from shopping_mall group by location");
        Combo3 = Tourism_App.sqlstringData;
        gc.setstringData("SELECT weather_region from weather");
        Combo4 = Tourism_App.sqlstringData;
        
        initComponents();
        
        //Scrolling Text Code
        ScrollingText st1 = new ScrollingText();
        ScrollingText st2 = new ScrollingText();
        ScrollingText st3 = new ScrollingText();
        jPanel2.add(st1);
        jPanel5.add(st2);
        jPanel6.add(st3);
        st1.setLocation(0, 0);
        st1.setSize(1360, 40);
        st2.setLocation(0, 0);
        st2.setSize(1360, 40);
        st3.setLocation(0, 0);
        st3.setSize(1360, 40);
        jTabbedPane1.setForegroundAt(0, new Color(13, 60, 33));
        jTabbedPane1.setForegroundAt(1, new Color(159, 28, 28));
        jTabbedPane1.setForegroundAt(2, Color.black);
        jTabbedPane1.setForegroundAt(3, new Color(36, 29, 109));
        jTabbedPane2.setBackground(Color.black);
        
        //Home Page
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        
        //Places Page
        jComboBox5.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jScrollPane5.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane7.setVisible(false);
        jScrollPane8.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel17.setVisible(false);
        
        //Booking Page
        
        setVisible(true);
        setSize(1366, 758);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tourism Website");
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(192, 240, 39));
        jTabbedPane1.setForeground(new java.awt.Color(153, 28, 28));
        jTabbedPane1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1354, 660));

        jTabbedPane2.setBackground(new java.awt.Color(33, 33, 33));
        jTabbedPane2.setForeground(new java.awt.Color(159, 28, 28));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Padauk", 1, 18)); // NOI18N

        jPanel6.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Combo1));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox1);
        jComboBox1.setBounds(530, 70, 200, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(0, 110, 452, 402);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Select a Location:");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(400, 70, 120, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/accomodation.png"))); // NOI18N
        jPanel6.add(jLabel3);
        jLabel3.setBounds(0, 0, 1219, 670);

        jTabbedPane2.addTab("Accomodation", jPanel6);

        jPanel2.setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(Combo2));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(530, 70, 200, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 120, 452, 402);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 255, 0));
        jLabel20.setText("Select a Location:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(400, 70, 120, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/home.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1219, 670);

        jTabbedPane2.addTab("Restaurant", jPanel2);

        jPanel5.setLayout(null);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(Combo3));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(530, 70, 200, 20);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanel5.add(jScrollPane4);
        jScrollPane4.setBounds(0, 120, 452, 402);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 255));
        jLabel21.setText("Select a Location:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(400, 70, 120, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/mall.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 0, 1219, 670);

        jTabbedPane2.addTab("Shopping Mall", jPanel5);

        jTabbedPane1.addTab("Home", jTabbedPane2);

        jPanel1.setLayout(null);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(Combo4));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(420, 20, 200, 20);

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(800, 20, 200, 20);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 60, 800, 300);

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("URW Palladio L", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(60, 156, 43));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/left_converted.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 60, 90, 300);

        jButton2.setBackground(new java.awt.Color(255, 250, 250));
        jButton2.setFont(new java.awt.Font("URW Palladio L", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(53, 73, 180));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/right_converted.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1110, 60, 90, 300);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(10, 370, 660, 100);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable6);

        jPanel1.add(jScrollPane7);
        jScrollPane7.setBounds(10, 510, 660, 100);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable7);

        jPanel1.add(jScrollPane8);
        jScrollPane8.setBounds(680, 510, 660, 100);

        jScrollPane1.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(680, 370, 660, 100);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Weather");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 340, 130, 22);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("Transportation");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 490, 130, 22);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Emergency");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(680, 490, 130, 22);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Select a Spot:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(700, 20, 90, 20);

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Select a Location:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(300, 20, 120, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/placebackground.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1, 1, 1360, 620);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(530, 220, 56, 20);

        jTabbedPane1.addTab("Places", jPanel1);

        jPanel3.setLayout(null);

        jButton4.setForeground(new java.awt.Color(15, 7, 239));
        jButton4.setText("LOGIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(520, 380, 150, 23);

        jButton5.setForeground(new java.awt.Color(49, 123, 38));
        jButton5.setText("SIGN-UP");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(690, 380, 150, 23);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(630, 220, 200, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(630, 170, 200, 20);

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Username: ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(540, 170, 80, 30);

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(226, 4, 4));
        jLabel11.setText("Password:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(540, 220, 80, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/booking.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 1354, 608);

        jTabbedPane1.addTab("Booking Info", jPanel3);

        jPanel4.setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1);
        jTextField1.setBounds(390, 90, 200, 20);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(780, 90, 200, 20);

        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(600, 540, 150, 23);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("USER NAME");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(430, 60, 120, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PASSWORD");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(820, 60, 120, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/admin.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 0, 1354, 608);

        jTabbedPane1.addTab("Admin", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 68, 1354, 660);

        jLabel5.setFont(new java.awt.Font("Rachana", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(167, 59, 59));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BANGLADESHI SPOTS");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1366, 62);

        jLabel1.setFont(new java.awt.Font("Rachana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(167, 59, 59));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/wallpaper-dark4.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        //System.out.println(selected);
        gc.set2DData("select  acco_name, type, offers, phone, email, website from accomodation where location = '"+selected+"'");
        Object []columnNames = { "Name", "Type", "Offers", "Contact", "Email", "Website" };
        jTable1.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames));
        jTable1.setRowHeight(30);
        jTable1.setEnabled(false);
        jScrollPane2.setSize(1219, jTable1.getRowHeight()*jTable1.getRowCount()+25);
        jScrollPane2.setViewportView(jTable1);

        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        //System.out.println(selected);
        gc.set2DData("select  res_name, address, phone, email, website, description from restaurant where location = '"+selected+"'");
        Object []columnNames = { "Name", "Address", "Contact", "Email", "Website", "Description" };
        jTable2.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames));
        jTable2.setRowHeight(30);
        jTable2.setEnabled(false);
        jScrollPane3.setSize(1219, jTable2.getRowHeight()*jTable2.getRowCount()+25);
        jScrollPane3.setViewportView(jTable2);

        jScrollPane3.setVisible(true);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        //System.out.println(selected);
        gc.set2DData("select  sp_name, category, address from shopping_mall where location = '"+selected+"'");
        Object []columnNames = { "Name", "Category", "Address" };
        jTable3.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames));
        jTable3.setRowHeight(30);
        jTable3.setEnabled(false);
        jScrollPane4.setSize(1219, jTable3.getRowHeight()*jTable3.getRowCount()+25);
        jScrollPane4.setViewportView(jTable3);

        jScrollPane4.setVisible(true);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        gc.setstringData("SELECT place_name from place where location = '"+selected+"'");
        Combo5 = Tourism_App.sqlstringData;
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(Combo5));
        jComboBox5.setVisible(true);
        jLabel9.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jScrollPane5.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane7.setVisible(false);
        jScrollPane8.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel17.setVisible(true);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        gc.setstringData("SELECT place_id from place where place_name = '"+selected+"'");
        String id = Tourism_App.sqlstringData[0];
        //System.out.println(id);
        gc.setImageData("SELECT image from photo where place_id ='"+id+"'");
        ImageIcon img = new ImageIcon(Tourism_App.image[0]);
        /*Image im = img.getImage();
        Image myImg = im.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(myImg);*/
        jLabel9.setIcon(img);
        jLabel9.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        piccount=0;
        
        selected = (String)jComboBox4.getSelectedItem();
        
        //Table for Weather
        gc.set2DData("select  min_temp, max_temp, min_rainfall, max_rainfall from weather where weather_region = '"+selected+"'");
        Object []columnNames1 = { "Temperature(Min)", "Temperature(Max)", "Rainfall(Min)", "Rainfall(Max)" };
        jTable4.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames1));
        jTable4.setEnabled(false);
        jScrollPane5.setViewportView(jTable4);

        jScrollPane5.setVisible(true);
        
        //Text Area for Description
        gc.setstringData("select address from place where location = '"+selected+"'");
        String add = Tourism_App.sqlstringData[0];
        gc.setstringData("select description from place where location = '"+selected+"'");
        String des = Tourism_App.sqlstringData[0];
        jTextArea1.setText("Description:\n"+des+"\n\nAddress:\n"+add);
        
        jScrollPane1.setVisible(true);
        
        //Table for Transportation
        gc.set2DData("select  tran_name, category, phone, email, website, address from transportation where area = '"+selected+"'");
        Object []columnNames3 = { "Name", "Type", "Contact", "Email", "Website", "Address" };
        jTable6.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames3));
        jTable6.setEnabled(false);
        jScrollPane7.setViewportView(jTable6);

        jScrollPane7.setVisible(true);
        
        //Table for Emergency
        gc.set2DData("select  emr_name, emr_type, address, phone, email, website from emergency where location = '"+selected+"'");
        Object []columnNames4 = { "Name", "Type", "Address", "Contact", "Email", "Website" };
        jTable7.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable7.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames4));
        jTable7.setEnabled(false);
        jScrollPane8.setViewportView(jTable7);

        jScrollPane8.setVisible(true);
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        piccount--;
        if(piccount==-1) piccount = Tourism_App.imagecount-1;
        
        ImageIcon img = new ImageIcon(Tourism_App.image[piccount]);
        /*Image im = img.getImage();
        Image myImg = im.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(myImg);*/
        jLabel9.setIcon(img);
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        piccount++;
        if(piccount==Tourism_App.imagecount) piccount = 0;
        
        ImageIcon img = new ImageIcon(Tourism_App.image[piccount]);
        /*Image im = img.getImage();
        Image myImg = im.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(myImg);*/
        jLabel9.setIcon(img);
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String user = jTextField1.getText();
        String pass = jPasswordField1.getText();
        gc.setstringData("select * from users where user_name = '"+user+"' and user_password = '"+pass+"'");
        if(Tourism_App.sqlstringData.length!=0)
        {
            adminpage ap = new adminpage();
            ap.setSize(1366, 760);
            ap.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String user = jTextField2.getText();
        String pass = jPasswordField2.getText();
        gc.setstringData("select u_name, u_password from project_users where u_name = '"+user+"' and u_password = '"+pass+"'");
        if(Tourism_App.sqlstringData.length==0)
        {
            JOptionPane.showMessageDialog(null, "Invalid Username/Password!\nPlease re-enter.", "Validation", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            u_name = user;
            BookingFrame bf = new BookingFrame();
            bf.setSize(1366, 760);
            bf.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        UserForm uf = new UserForm();
        uf.setSize(1366, 760);
        uf.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
