/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourism_app;

import java.sql.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author talha
 */
public class BookingFrame extends javax.swing.JFrame {

    String Combo1[];
    getConnection gc = new getConnection();
    /**
     * Creates new form BookingFrame
     */
    public BookingFrame() {
        gc.setstringData("SELECT location from accomodation group by location");
        Combo1 = Tourism_App.sqlstringData;
        initComponents();
        jScrollPane1.setVisible(false);
        //jDateChooser1.setDateFormatString(string);
    }
    public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
        if(date != null) {
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 760));
        getContentPane().setLayout(null);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(Combo1));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(270, 210, 200, 27);

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(36, 214, 60));
        jLabel14.setText("Location:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(180, 210, 80, 30);

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(23, 229, 240));
        jLabel13.setText("Accomodation:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(540, 210, 110, 30);

        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(660, 210, 200, 27);

        jButton7.setForeground(new java.awt.Color(80, 77, 163));
        jButton7.setText("BOOK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1140, 640, 130, 31);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable8.setEnabled(false);
        jScrollPane1.setViewportView(jTable8);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 280, 590, 320);

        jButton4.setForeground(new java.awt.Color(15, 7, 239));
        jButton4.setText("My Bookings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 70, 150, 31);

        jButton1.setForeground(new java.awt.Color(234, 17, 17));
        jButton1.setLabel("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 640, 130, 31);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(1050, 210, 111, 27);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 229, 240));
        jLabel2.setText("Date of Booking:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(920, 210, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/city.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String selected = (String)cb.getSelectedItem();
        //System.out.println(selected);
        gc.setstringData("select acco_name from accomodation where location = '"+selected+"'");
        jComboBox7.setVisible(true);
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(Tourism_App.sqlstringData));
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Date date = convertUtilDateToSqlDate(jDateChooser1.getDate());
        gc.setstringData("select u_id from project_users where u_name = '"+HomePage.u_name+"'");
        String u_id = Tourism_App.sqlstringData[0];
        gc.setstringData("select acco_id from accomodation where acco_name = '"+(String)jComboBox7.getSelectedItem()+"'");
        String acco_id = Tourism_App.sqlstringData[0];
        //JOptionPane.showMessageDialog(null, u_id + " " + (String)jComboBox7.getSelectedItem());
        gc.insertData("insert into booking (u_id, acco_id, booking_date) values('"+u_id+"','"+acco_id+"','"+date+"')");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String selected = HomePage.u_name;
        gc.set2DData("select booking_id, u_name, acco_name, booking_date from booking natural join accomodation "
                + "natural join project_users where u_name = '"+selected+"'");
        Object []columnNames4 = { "ID", "Name", "Accomodation", "Date of Booking" };
        jTable8.setFont(new java.awt.Font("Noto Serif", 1, 10)); // NOI18N
        jTable8.setModel(new javax.swing.table.DefaultTableModel(Tourism_App.sql2DData, columnNames4));
        jTable8.setEnabled(false);
        jScrollPane1.setViewportView(jTable8);

        jScrollPane1.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable8;
    // End of variables declaration//GEN-END:variables
}
