/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourism_app;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author talha
 */
public class picframe extends javax.swing.JFrame {

    getConnection gc = new getConnection();
    private static final String CONNECTION =
                          "jdbc:mysql://localhost/talha?autoReconnect=true&useSSL=false";
    Connection c;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    String s;
    String Combo1[];
    /**
     * Creates new form picframe
     */
    public picframe() {
        gc = new getConnection();
        gc.setstringData("SELECT place_name from place");
        Combo1 = Tourism_App.sqlstringData;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(135, 81, 800, 300);

        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1085, 81, 163, 68);

        jButton2.setText("ADD IMAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1085, 313, 163, 68);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Combo1));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(88, 509, 200, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(521, 509, 200, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1048, 509, 200, 20);

        jLabel2.setText("File Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(403, 507, 100, 30);

        jLabel3.setText("Image Description:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 507, 160, 30);

        jButton3.setText("DONE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1163, 653, 100, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourism_app/photoback.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1366, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        filechooser.addChoosableFileFilter(filter);
        int result = filechooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = filechooser.getSelectedFile();
            s = selectedFile.getAbsolutePath();
            BufferedImage img = null;
            try {
                img = ImageIO.read(selectedFile);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            ImageIcon icon = new ImageIcon(img);
            jLabel1.setIcon(icon);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String place_name = (String)jComboBox1.getSelectedItem();
            gc.setstringData("select place_id from place where place_name = '"+place_name+"'");
            String place_id = Tourism_App.sqlstringData[0];
            String filename = jTextField1.getText();
            String mimetype = jTextField2.getText();
            c = DriverManager.getConnection(CONNECTION, "root", "shahriar");
            ps = c.prepareStatement("insert into photo (place_id, image, filename, mimetype) values (?,?,?,?)");
            InputStream is = new FileInputStream(new File(s));
            ps.setString(1, place_id);
            ps.setBlob(2, is);
            ps.setString(3, filename);
            ps.setString(4, mimetype);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Inserted");
        }
        catch(Exception e){
          //Handle errors for JDBC
          JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                ps.close();
                c.close();
            }
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null, se);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(picframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(picframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(picframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(picframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new picframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
