/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iut_cafeteria_inv;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author talha
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //jTextArea1.setBackground(new Color(red, green, blue, alpha));
        jScrollPane1.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jButton1.setVisible(false);
        jScrollPane2.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
        jLabel29.setVisible(false);
        jLabel23.setVisible(false);
        jComboBox7.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jButton8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));

        jTabbedPane1.setBackground(new java.awt.Color(15, 15, 15));
        jTabbedPane1.setForeground(new java.awt.Color(255, 45, 0));
        jTabbedPane1.setFont(new java.awt.Font("Phetsarath OT", 1, 24)); // NOI18N
        jTabbedPane1.setName("Main App"); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Purisa", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 253, 241));
        jLabel2.setText("Welcome to the Home page of IUT Cafeteria Inventory!!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 0, 850, 60);

        jLabel3.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 255, 0));
        jLabel3.setText("Assalamu Alaikum Assistant Supervisor Sir,");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 60, 430, 29);

        jLabel4.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 255, 0));
        jLabel4.setText("To see and modify the present items in the inventory go to the \"Inventory\" tab. To Create Polls for taking attendance for");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 1220, 30);

        jLabel5.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 255, 0));
        jLabel5.setText("the upcoming meals and to create menu options for choice prioritization of students and teachers go to the \"Polls\" tab.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 120, 1080, 29);

        jLabel7.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 64, 10));
        jLabel7.setText("If you face any Problems please be sure to notify us!");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 600, 470, 29);

        jLabel8.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 64, 10));
        jLabel8.setText("      - From the Developer Team, IUT CSE'14 -");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 630, 470, 29);

        jLabel1.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 35, 15));
        jLabel1.setText("You can check usage data of the inventory, attendance data and menu choice of the students and teachers in");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 310, 1010, 30);

        jLabel9.setFont(new java.awt.Font("Sawasdee", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 35, 15));
        jLabel9.setText("the \"Statistics\" tab. And see and set feedback in \"Feedback\" tab.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 340, 600, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iut_cafeteria_inv/home.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(7, 7, 1340, 710);

        jTabbedPane1.addTab("Home", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleDescription("");
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        jTabbedPane2.setBackground(new java.awt.Color(44, 73, 93));
        jTabbedPane2.setForeground(new java.awt.Color(28, 152, 7));
        jTabbedPane2.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        jTabbedPane2.setOpaque(true);

        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(169, 29, 29));
        jLabel11.setText("Item Type:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(570, 20, 78, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Not Selected>", "Meat/Fish", "Crops & Spices", "Vegetables & Others", "Disposable Items", "Utensils" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(650, 20, 180, 30);

        jTable1.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 1270, 370);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iut_cafeteria_inv/inventory.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 1342, 680);

        jTabbedPane2.addTab("CHECK INVENTORY", jPanel2);

        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Rachana", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Insert Item:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(130, 50, 100, 30);

        jLabel15.setFont(new java.awt.Font("Rachana", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Delete Item:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(130, 130, 120, 30);

        jLabel16.setFont(new java.awt.Font("Rachana", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(254, 254, 254));
        jLabel16.setText("Update Item:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(130, 210, 130, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Not Selected>", "Meat/Fish", "Crops & Spices", "Vegetables & Others", "Disposable Items", "Utensils" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(260, 40, 180, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Not Selected>", "Meat/Fish", "Crops & Spices", "Vegetables & Others", "Disposable Items", "Utensils" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3);
        jComboBox3.setBounds(260, 120, 180, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Not Selected>", "Meat/Fish", "Crops & Spices", "Vegetables & Others", "Disposable Items", "Utensils" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(260, 200, 180, 30);

        jTextField1.setToolTipText("Enter Name Here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(510, 40, 150, 30);

        jTextField2.setToolTipText("Enter Amount Here (in kg for 'Meat/Fish', 'Vegetables & Others' and 'Crops & Spices' , in Quantity for the rest)");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(680, 40, 150, 30);

        jTextField3.setToolTipText("Enter the Total Price Here");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(850, 40, 150, 30);

        jButton1.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 18, 18));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1050, 40, 160, 27);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(510, 120, 200, 50);

        jButton2.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 18, 18));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(740, 200, 160, 27);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox5);
        jComboBox5.setBounds(510, 200, 200, 27);

        jTextField4.setToolTipText("Enter Name Here");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(510, 290, 150, 30);

        jTextField5.setToolTipText("Enter Amount Here (in kg for 'Meat/Fish', 'Vegetables & Others' and 'Crops & Spices' , in Quantity for the rest)");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(680, 290, 150, 30);

        jTextField6.setToolTipText("Enter the Total Price Here");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField6);
        jTextField6.setBounds(850, 290, 150, 30);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(50, 44, 201));
        jLabel17.setText("Present Value:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(320, 260, 160, 22);

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(19, 115, 26));
        jLabel19.setText("Updated Value:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(320, 300, 160, 22);

        jTextField7.setEditable(false);
        jTextField7.setToolTipText("Enter Name Here");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField7);
        jTextField7.setBounds(510, 250, 150, 30);

        jTextField8.setEditable(false);
        jTextField8.setToolTipText("Enter Amount Here (in kg for 'Meat/Fish', 'Vegetables & Others' and 'Crops & Spices' , in Quantity for the rest)");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField8);
        jTextField8.setBounds(680, 250, 150, 30);

        jTextField9.setEditable(false);
        jTextField9.setToolTipText("Enter the Total Price Here");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9);
        jTextField9.setBounds(850, 250, 150, 30);

        jButton3.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(254, 18, 18));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(740, 120, 160, 27);

        jLabel13.setForeground(new java.awt.Color(224, 99, 21));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iut_cafeteria_inv/inventory.png"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 0, 1342, 680);

        jTabbedPane2.addTab("EDIT INVENTORY", jPanel3);

        jTabbedPane1.addTab("Inventory", jTabbedPane2);

        jPanel4.setLayout(null);

        jButton4.setText("Create Polls for Attendance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(550, 90, 240, 31);

        jButton5.setText("Create Polls for Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(550, 160, 240, 31);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Lunch", "Dinner" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox6);
        jComboBox6.setBounds(560, 240, 120, 27);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField10);
        jTextField10.setBounds(760, 240, 120, 27);

        jLabel21.setFont(new java.awt.Font("Noto Sans UI", 1, 14)); // NOI18N
        jLabel21.setText("Date:");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(720, 240, 40, 30);

        jButton8.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(234, 21, 21));
        jButton8.setText("SUBMIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(1140, 600, 110, 31);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox7);
        jComboBox7.setBounds(550, 440, 44, 27);

        jLabel22.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        jLabel22.setText("Menu Item Count:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(400, 450, 160, 18);

        jLabel23.setFont(new java.awt.Font("Noto Sans UI", 1, 14)); // NOI18N
        jLabel23.setText("Meal Type:");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(480, 240, 90, 30);

        jLabel24.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel24.setText("Item 1:");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(640, 450, 60, 20);

        jLabel25.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel25.setText("Item 2:");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(640, 480, 60, 20);

        jLabel26.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel26.setText("Item 3:");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(640, 510, 60, 20);

        jLabel27.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel27.setText("Item 4:");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(640, 540, 60, 20);

        jLabel28.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel28.setText("Item 5:");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(640, 570, 60, 20);

        jLabel29.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel29.setText("Item 6:");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(640, 600, 60, 20);

        jPanel4.add(jTextField11);
        jTextField11.setBounds(700, 440, 180, 27);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField12);
        jTextField12.setBounds(700, 470, 180, 27);

        jPanel4.add(jTextField13);
        jTextField13.setBounds(700, 500, 180, 27);

        jPanel4.add(jTextField14);
        jTextField14.setBounds(700, 530, 180, 27);

        jPanel4.add(jTextField15);
        jTextField15.setBounds(700, 560, 180, 27);

        jPanel4.add(jTextField16);
        jTextField16.setBounds(700, 590, 180, 27);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iut_cafeteria_inv/facebook.jpg"))); // NOI18N
        jPanel4.add(jLabel18);
        jLabel18.setBounds(12, 12, 1330, 701);

        jTabbedPane1.addTab("Polls", jPanel4);

        jPanel5.setLayout(null);

        jButton6.setText("Check Menu Choice Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(680, 30, 220, 31);

        jButton7.setText("Check Attendance Data");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(410, 30, 220, 31);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iut_cafeteria_inv/stat1.png"))); // NOI18N
        jLabel20.setName(""); // NOI18N
        jPanel5.add(jLabel20);
        jLabel20.setBounds(0, 0, 1354, 725);

        jTabbedPane1.addTab("Statistics", jPanel5);

        jPanel6.setLayout(null);

        jButton9.setBackground(new java.awt.Color(16, 21, 248));
        jButton9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(252, 245, 245));
        jButton9.setText("Go to Facebook");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(590, 120, 190, 31);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iut_cafeteria_inv/feedback.jpg"))); // NOI18N
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 1360, 710);

        jTabbedPane1.addTab("Feedback", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String str = (String)cb.getSelectedItem();
        if(str.equals("Meat/Fish"))
        {
            jTable1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {"Beef", 40, null, null},
                    {"Mutton", 20, null, null},
                    {"Kima", 10, null, null},
                    {"Chicken", 10, null, null},
                    {"Broiler", 15, null, null},
                    {"Fish", 5, null, null},
                    {"Shutki", 4, null, null}
                },
                new String [] {
                    "Name", "Amount (kg)", "Price", "Date"
                }
            ));
            jTable1.setRowHeight(30);
            jTable1.setEnabled(false);
            jScrollPane1.setSize(jTable1.getWidth(), jTable1.getRowHeight()*jTable1.getRowCount()+25);
            jScrollPane1.setViewportView(jTable1);
            
            jScrollPane1.setVisible(true);
        }
        else if(str.equals("Crops & Spices"))
        {
            jTable1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {"Polao", null, null, null},
                    {"Boiled", null, null, null},
                    {"Flour", null, null, null},
                    {"Atta", null, null, null},
                    {"Mug (Dal)", null, null, null},
                    {"But (Dal)", null, null, null},
                    {"Cumin Seed (Jira)", null, null, null},
                    {"M. Seed (Shorisha)", null, null, null},
                    {"Chilli (Morich)", null, null, null},
                    {"Pepper (Gura Morich)", null, null, null},
                    {"Dhoniyar Gura", null, null, null},
                    {"Onions", null, null, null}
                },
                new String [] {
                    "Name", "Amount (kg)", "Price", "Date"
                }
            ));
            jTable1.setRowHeight(30);
            jTable1.setEnabled(false);
            jScrollPane1.setSize(jTable1.getWidth(), jTable1.getRowHeight()*jTable1.getRowCount()+25);
            jScrollPane1.setViewportView(jTable1);
            jScrollPane1.setVisible(true);
        }
        else if(str.equals("Vegetables & Others"))
        {
            jTable1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {"Cabbage", null, null, null},
                    {"Potato", null, null, null},
                    {"Carrot", null, null, null},
                    {"Cucumber", null, null, null},
                    {"Lemon", null, null, null},
                    {"Spinach (Green)", null, null, null},
                    {"Papaya", null, null, null},
                    {"Yeast", null, null, null},
                    {"Oil", null, null, null},
                    {"Sugar", null, null, null},
                    {"Vinegar", null, null, null},
                    {"Raisin", null, null, null}
                },
                new String [] {
                    "Name", "Amount (kg)", "Price", "Date"
                }
            ));
            jTable1.setRowHeight(30);
            jTable1.setEnabled(false);
            jScrollPane1.setSize(jTable1.getWidth(), jTable1.getRowHeight()*jTable1.getRowCount()+25);
            jScrollPane1.setViewportView(jTable1);
            jScrollPane1.setVisible(true);
        }
        else if(str.equals("Disposable Items"))
        {
            jTable1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {"Flavoured Milk (Igloo)", null, null, null},
                    {"Juice (Pran)", null, null, null},
                    {"Juice (Starship)", null, null, null},
                    {"Ice Cream", null, null, null},
                    {"Vim Bar", null, null, null},
                    {"Curd", null, null, null},
                    {"Banana", null, null, null},
                    {"Tea Bag", null, null, null},
                    {"Jet Bar", null, null, null},
                    {"Custard", null, null, null},
                    {"Noodles", null, null, null},
                    {"Shuji", null, null, null},
                    {"Eggs", null, null, null},
                    {"Body Soap", null, null, null}
                },
                new String [] {
                    "Name", "Amount (Quantity)", "Price", "Date"
                }
            ));
            jTable1.setRowHeight(30);
            jTable1.setEnabled(false);
            jScrollPane1.setSize(jTable1.getWidth(), jTable1.getRowHeight()*jTable1.getRowCount()+25);
            jScrollPane1.setViewportView(jTable1);
            jScrollPane1.setVisible(true);
        }
        else if(str.equals("Utensils"))
        {
            jTable1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {"Plates (Large)", null, null, null},
                    {"Plates (Flat)", null, null, null},
                    {"Glasses", null, null, null},
                    {"Plates (Small)", null, null, null},
                    {"Spoons (Large)", null, null, null},
                    {"Spoons (Small)", null, null, null},
                    {"Forks", null, null, null},
                    {"Knives", null, null, null},
                    {"Trays (Curry)", null, null, null},
                    {"Saucepan (Korai)", null, null, null},
                    {"Mixer/Stirer", null, null, null},
                    {"Jugs", null, null, null},
                    {"Chair-Table Sets", null, null, null},
                    {"Salt Containers", null, null, null},
                    {"Trays (Flat)", null, null, null}
                },
                new String [] {
                    "Name", "Amount (Quantity)", "Price", "Date"
                }
            ));
            jTable1.setRowHeight(30);
            jTable1.setEnabled(false);
            jScrollPane1.setSize(jTable1.getWidth(), jTable1.getRowHeight()*jTable1.getRowCount()+25);
            jScrollPane1.setViewportView(jTable1);
            jScrollPane1.setVisible(true);
        }
        else jScrollPane1.setVisible(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String str = (String)cb.getSelectedItem();
        if(!str.equals("<Not Selected>"))
        {
            jScrollPane1.setVisible(true);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jButton1.setVisible(true);
        }
        else
        {
            jScrollPane1.setVisible(false);
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
            jButton1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String str = (String)cb.getSelectedItem();
        if(str.equals("Meat/Fish"))
        {
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {"Beef", "Mutton", "Kima", "Chicken", "Broiler", "Fish", "Shutki" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane2.setSize(jScrollPane2.getWidth(), 7*18);
            jScrollPane2.setViewportView(jList1);
            jScrollPane2.setVisible(true);
            jButton3.setVisible(true);
        }
        else if(str.equals("Crops & Spices"))
        {
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {"Polao","Boiled","Flour","Atta","Mug (Dal)","But (Dal)","Cumin Seed (Jira)","M. Seed (Shorisha)","Chilli (Morich)","Pepper (Gura Morich)","Dhoniyar Gur", "Onions" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane2.setSize(jScrollPane2.getWidth(), 12*18);
            jScrollPane2.setViewportView(jList1);
            jScrollPane2.setVisible(true);
            jButton3.setVisible(true);
        }
        else if(str.equals("Vegetables & Others"))
        {
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {"Cabbage","Potato","Carrot","Cucumber","Lemon","Spinach (Green)","Papaya","Yeast","Oil","Sugar","Vinegar","Raisin" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane2.setSize(jScrollPane2.getWidth(), 12*18);
            jScrollPane2.setViewportView(jList1);
            jScrollPane2.setVisible(true);
            jButton3.setVisible(true);
        }
        else if(str.equals("Disposable Items"))
        {
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {"Flavoured Milk (Igloo)","Juice (Pran)","Juice (Starship)","Ice Cream","Vim Bar","Curd","Banana","Tea Bag","Jet Bar","Custard","Noodles","Shuji","Eggs","Body Soap"};
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane2.setSize(jScrollPane2.getWidth(), 14*18);
            jScrollPane2.setViewportView(jList1);
            jScrollPane2.setVisible(true);
            jButton3.setVisible(true);
        }
        else if(str.equals("Utensils"))
        {
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {"Plates (Large)","Plates (Flat)","Glasses","Plates (Small)","Spoons (Large)","Spoons (Small)","Forks","Knives","Trays (Curry)","Saucepan (Korai)","Mixer/Stirer","Jugs","Chair-Table Sets","Salt Containers","Trays (Flat)"};
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane2.setSize(jScrollPane2.getWidth(), 15*18);
            jScrollPane2.setViewportView(jList1);
            jScrollPane2.setVisible(true);
            jButton3.setVisible(true);
        }
        else
        {
            jScrollPane2.setVisible(false);
            jButton3.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String str = (String)cb.getSelectedItem();
        if(str.equals("Meat/Fish"))
        {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beef", "Mutton", "Kima", "Chicken", "Broiler", "Fish", "Shutki" }));
            jComboBox5.setVisible(true);
            jButton2.setVisible(true);
        }
        else if(str.equals("Crops & Spices"))
        {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Polao","Boiled","Flour","Atta","Mug (Dal)","But (Dal)","Cumin Seed (Jira)","M. Seed (Shorisha)","Chilli (Morich)","Pepper (Gura Morich)","Dhoniyar Gur", "Onions" }));
            jComboBox5.setVisible(true);
            jButton2.setVisible(true);
        }
        else if(str.equals("Vegetables & Others"))
        {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Cabbage","Potato","Carrot","Cucumber","Lemon","Spinach (Green)","Papaya","Yeast","Oil","Sugar","Vinegar","Raisin" }));
            jComboBox5.setVisible(true);
            jButton2.setVisible(true);
        }
        else if(str.equals("Disposable Items"))
        {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flavoured Milk (Igloo)","Juice (Pran)","Juice (Starship)","Ice Cream","Vim Bar","Curd","Banana","Tea Bag","Jet Bar","Custard","Noodles","Shuji","Eggs","Body Soap"}));
            jComboBox5.setVisible(true);
            jButton2.setVisible(true);
        }
        else if(str.equals("Utensils"))
        {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plates (Large)","Plates (Flat)","Glasses","Plates (Small)","Spoons (Large)","Spoons (Small)","Forks","Knives","Trays (Curry)","Saucepan (Korai)","Mixer/Stirer","Jugs","Chair-Table Sets","Salt Containers","Trays (Flat)"}));
            jComboBox5.setVisible(true);
            jButton2.setVisible(true);
        }
        else
        {
            jComboBox5.setVisible(false);
            jButton2.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Your Item has been Updated.", "Insertion Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        menu demo = new menu( "Menu Choices" );  
        demo.setSize( 1366 , 668 );    
        RefineryUtilities.centerFrameOnScreen( demo );    
        demo.setVisible( true );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        attendance demo = new attendance( "Attendance" );  
        demo.setSize( 1366 , 668 );    
        RefineryUtilities.centerFrameOnScreen( demo );    
        demo.setVisible( true );
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jComboBox6.setVisible(true);
        jLabel21.setVisible(true);
        jLabel23.setVisible(true);
        jTextField10.setVisible(true);
        jButton8.setVisible(true);
        
        jComboBox7.setVisible(false);
        jLabel22.setVisible(false);
        jLabel24.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jComboBox6.setVisible(true);
        jComboBox7.setVisible(true);
        jLabel21.setVisible(true);
        jLabel22.setVisible(true);
        jLabel23.setVisible(true);
        jLabel24.setVisible(true);
        jTextField10.setVisible(true);
        jTextField11.setVisible(true);
        jButton8.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Your Item has been Inserted.", "Insertion Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Your Item(s) has been Deleted.", "Insertion Message", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        openWebPage("http://www.facebook.com/");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        JComboBox cb = (JComboBox)evt.getSource();
        String str = (String)cb.getSelectedItem();
        if(str.equals("2"))
        {
            jLabel25.setVisible(true);
            jTextField12.setVisible(true);
        }
        else if(str.equals("3"))
        {
            jLabel25.setVisible(true);
            jTextField12.setVisible(true);
            jLabel26.setVisible(true);
            jTextField13.setVisible(true);
        }
        else if(str.equals("4"))
        {
            jLabel25.setVisible(true);
            jTextField12.setVisible(true);
            jLabel26.setVisible(true);
            jTextField13.setVisible(true);
            jLabel27.setVisible(true);
            jTextField14.setVisible(true);
        }
        else if(str.equals("5"))
        {
            jLabel25.setVisible(true);
            jTextField12.setVisible(true);
            jLabel26.setVisible(true);
            jTextField13.setVisible(true);
            jLabel27.setVisible(true);
            jTextField14.setVisible(true);
            jLabel28.setVisible(true);
            jTextField15.setVisible(true);
        }
        else if(str.equals("6"))
        {
            jLabel25.setVisible(true);
            jTextField12.setVisible(true);
            jLabel26.setVisible(true);
            jTextField13.setVisible(true);
            jLabel27.setVisible(true);
            jTextField14.setVisible(true);
            jLabel28.setVisible(true);
            jTextField15.setVisible(true);
            jLabel29.setVisible(true);
            jTextField16.setVisible(true);
        }
        jLabel24.setVisible(true);
        jTextField11.setVisible(true);
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        openWebPage("http://www.facebook.com/");
    }//GEN-LAST:event_jButton9ActionPerformed
    public void openWebPage(String url){
       try {         
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
